CREATE TABLE ERIC_45G_EUTRANCELLRELATION
(
BEGINTIME DATE,
ELEMENT VARCHAR2(100 BYTE),
ENDTIME DATE,
UTRANCELL VARCHAR2(100 BYTE),
pmHoExeAttLteInterF VARCHAR2(250 BYTE),
pmHoExeAttLteIntraF VARCHAR2(250 BYTE),
pmHoExeAttNonMob VARCHAR2(250 BYTE),
pmHoExeSuccLteInterF VARCHAR2(250 BYTE),
pmHoExeSuccLteIntraF VARCHAR2(250 BYTE),
pmHoExeSuccNonMob VARCHAR2(250 BYTE),
pmHoPrepAttLteInterF VARCHAR2(250 BYTE),
pmHoPrepAttLteIntraF VARCHAR2(250 BYTE),
pmHoPrepAttNonMob VARCHAR2(250 BYTE),
pmHoPrepSuccLteInterF VARCHAR2(250 BYTE),
pmHoPrepSuccLteIntraF VARCHAR2(250 BYTE),
pmHoPrepSuccNonMob VARCHAR2(250 BYTE),
DATETIME_INS TIMESTAMP (6),
DATETIME DATE
)
NOCACHE
  MONITORING
  PARTITION BY RANGE (DATETIME)
  (
  PARTITION p20180406 VALUES LESS THAN (TO_DATE('2018-04-06 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
  PCTFREE     10
  INITRANS    1
  MAXTRANS    255
  LOGGING
  )
/
